import { FlatCompat } from '@eslint/eslintrc';
import js from '@eslint/js';

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
  recommendedConfig: js.configs.recommended,
});

export default compat.config(
  {
    extends: [
      'plugin:react-hooks/recommended',
      'eslint:recommended',
      'plugin:@typescript-eslint/recommended',
    ],
    env: {
      es2021: true,
      browser: true,
      node: true,
      'jest/globals': true,
    },
    parser: '@typescript-eslint/parser',
    parserOptions: {
      ecmaFeatures: {
        jsx: true,
      },
      ecmaVersion: 12,
      sourceType: 'module',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
    plugins: ['react', 'unused-imports', '@typescript-eslint', 'import', 'react-refresh'],
    rules: {
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      'unused-imports/no-unused-imports': 'warn',
      eqeqeq: ['error', 'always'],
      'react/jsx-filename-extension': [1, { extensions: ['.tsx', '.jsx'] }],
      curly: ['error', 'all'],
      'consistent-return': 'error',
      'react/prop-types': 'error',
      'no-console': 'warn',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0, maxEOF: 0 }],
      indent: ['error', 2, {
        SwitchCase: 1,
        VariableDeclarator: 1,
        outerIIFEBody: 1,
        FunctionDeclaration: { parameters: 1, body: 1 },
        FunctionExpression: { parameters: 1, body: 1 },
        CallExpression: { arguments: 1 },
        ArrayExpression: 1,
        ObjectExpression: 1,
        ImportDeclaration: 1,
        flatTernaryExpressions: false,
        ignoredNodes: ['JSXElement', 'JSXElement > *', 'JSXAttribute', 'JSXIdentifier', 'JSXNamespacedName', 'JSXMemberExpression', 'JSXSpreadAttribute', 'JSXExpressionContainer', 'JSXOpeningElement', 'JSXClosingElement', 'JSXFragment', 'JSXOpeningFragment', 'JSXClosingFragment', 'JSXText', 'JSXEmptyExpression', 'JSXSpreadChild'],
        ignoreComments: false,
      }],
      'react/jsx-indent': ['error', 2],
      'react/jsx-indent-props': ['error', 2],
      quotes: ['error', 'single', { avoidEscape: true }],
      'no-template-curly-in-string': 'error',
      'comma-dangle': ['error', 'always-multiline'],
      'react/jsx-no-useless-fragment': 'error',
      'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never' }],
      'quote-props': ['error', 'as-needed', { keywords: false, unnecessary: true, numbers: false }],
      semi: ['error', 'always'],
      'semi-spacing': ['error', { before: false, after: true }],
      'semi-style': ['error', 'last'],
      'react/jsx-closing-bracket-location': ['error', 'line-aligned'],
      'react/self-closing-comp': 'error',
      'arrow-parens': ['error', 'always'],
      'object-curly-spacing': ['error', 'always'],
      'jsx-quotes': ['error', 'prefer-single'],
      'linebreak-style': ['error', 'unix'],
      '@typescript-eslint/no-empty-object-type': 'off',
      'react/jsx-wrap-multilines': [
        'error',
        {
          declaration: 'parens-new-line',
          assignment: 'parens-new-line',
          return: 'parens-new-line',
          arrow: 'parens-new-line',
          condition: 'parens-new-line',
          logical: 'parens-new-line',
          prop: 'parens-new-line',
        },
      ],
      'react/jsx-max-props-per-line': ['error', { maximum: 1, when: 'multiline' }],
      'react/jsx-one-expression-per-line': ['error', { allow: 'single-child' }],
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'react/jsx-tag-spacing': [
        'error',
        {
          closingSlash: 'never',
          beforeSelfClosing: 'always',
          afterOpening: 'never',
          beforeClosing: 'never',
        },
      ],
      'no-trailing-spaces': ['error', { skipBlankLines: false, ignoreComments: false }],
      'padded-blocks': ['error', { blocks: 'never', classes: 'never', switches: 'never' }, { allowSingleLineBlocks: true }],
      'space-before-blocks': 'error',
      'react/jsx-first-prop-new-line': ['error', 'multiline-multiprop'],
      'import/newline-after-import': 'error',
      'import/first': 'error',
      'import/no-self-import': 'error',
      'import/no-useless-path-segments': ['error', { commonjs: true }],
      'object-curly-newline': ['error', {
        ObjectExpression: { multiline: true, consistent: true },
        ObjectPattern: { multiline: true, consistent: true },
        ImportDeclaration: { multiline: true, consistent: true },
        ExportDeclaration: { multiline: true, consistent: true },
      }],
      'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
      'no-mixed-operators': ['error', {
        groups: [
          ['%', '**'],
          ['%', '+'],
          ['%', '-'],
          ['%', '*'],
          ['%', '/'],
          ['/', '*'],
          ['&', '|', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!=='],
          ['&&', '||'],
        ],
        allowSamePrecedence: false,
      }],
      'import/order': [
        'error',
        {
          groups: [['builtin', 'external'], ['internal'], ['index', 'parent', 'sibling'], ['unknown']],
          pathGroups: [
            { pattern: 'react', group: 'builtin', position: 'before' },
            { pattern: '<THIRD_PARTY_MODULES>', group: 'external', position: 'after' },
            { pattern: 'hooks/**', group: 'internal', position: 'before' },
            { pattern: 'context/**', group: 'internal', position: 'before' },
            { pattern: 'helpers/**', group: 'internal', position: 'before' },
            { pattern: 'hooks/**', group: 'internal', position: 'before' },
            { pattern: 'stores/**', group: 'internal', position: 'before' },
            { pattern: 'services/**', group: 'internal', position: 'before' },
            { pattern: 'components/**', group: 'internal', position: 'before' },
            { pattern: 'icons/**', group: 'internal', position: 'before' },
            { pattern: 'src/**', group: 'internal', position: 'before' },
            { pattern: 'styles/**', group: 'internal', position: 'before' },
            { pattern: '**css**', group: 'unknown', position: 'after' },
          ],
          pathGroupsExcludedImportTypes: ['builtin'],
          warnOnUnassignedImports: true,
          'newlines-between': 'always',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
);
