import { getHandler, postHandler } from 'src/helpers/api';

// Get all checklists with optional query params
export const getChecklists = (params: string) => getHandler({
  path: `checklists${params ? `?${params}` : ''}`,
});

// Create / save a single checklist
export const saveChecklist = (data: object) => postHandler({
  path: 'checklist',
  body: JSON.stringify(data),
});

// Delete a checklist by ID
export const deleteChecklist = (checklistId: number | string) => postHandler({
  path: `checklists/${checklistId}`,
  method: 'DELETE',
});

// Update a checklist by ID
export const updateChecklist = (checklistId: number | string, data: object) => postHandler({
  path: `checklists/${checklistId}`,
  method: 'PATCH',
  body: JSON.stringify(data),
});

// Generate a checklist with AI-assist
export const generateChecklist = (taskId: string, data: object) => postHandler({
  path: `checklists/${taskId}/generate-checklists`,
  body: JSON.stringify(data),
});

// Save an array of checklists generated by AI
export const saveChecklists = (data: object[]) => postHandler({
  path: 'checklists',
  body: JSON.stringify(data),
});
